version: "3"

services:
    mysql:
        image: mysql:8.0.33
        ports:
            - "127.0.0.1:33060:3306"
        environment:
            - MYSQL_USER=db
            - MYSQL_PASSWORD=db
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=db
        command: --default-authentication-plugin=mysql_native_password
        restart: always

    app:
        build:
            context: ./docker/php
        volumes:
            - .:/app
        depends_on:
            -   mysql

    nginx:
        image: nginx:latest
        ports:
            - "1234:80"
        volumes:
            - .:/app
            - ./docker/nginx/conf.d:/etc/nginx/conf.d
        depends_on:
            -   app
